import hre, { network } from "hardhat";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { createHash } from "node:crypto";
import { buildEddsa, buildPoseidon } from "circomlibjs";

/**
 * Deploys the Groth16 verifier and the registry to the running node, publishes three policies
 * whose issuer key matches the demo issuer the frontend uses, and writes the frontend's config.
 *
 * Roles: 0 registry admin (the verifier organisation), 1..4 holders submitting proofs.
 */
const { viem } = await network.connect();
const publicClient = await viem.getPublicClient();
const wallets = await viem.getWalletClients();
const [admin, alice, bob, carol] = wallets;
const wait = async (hash: `0x${string}`) => publicClient.waitForTransactionReceipt({ hash });

// the demo issuer: the same deterministic key the frontend derives from this label
const ISSUER_LABEL = "Demo KYC Provider";
const eddsa = await buildEddsa();
const poseidon = await buildPoseidon();
const priv = createHash("sha256").update(ISSUER_LABEL).digest();
const [Ax, Ay] = eddsa.prv2pub(priv);
const issuerPubX = poseidon.F.toObject(Ax).toString();
const issuerPubY = poseidon.F.toObject(Ay).toString();

const verifier = await viem.deployContract("Groth16Verifier", []);
const registry = await viem.deployContract("VouchRegistry", [admin.account.address, verifier.address]);
console.log("Groth16Verifier ", verifier.address);
console.log("VouchRegistry   ", registry.address);
console.log("issuer pub x    ", issuerPubX.slice(0, 24) + "…");

const DAY = 365;
const policies = [
  { name: "Over 18", issuerPubX, issuerPubY, minAgeDays: 18 * DAY, minBalance: 0n, requireAge: true, requireBalance: false, requireAccredited: false, maxClockSkewDays: 2, active: true },
  { name: "Accredited investor", issuerPubX, issuerPubY, minAgeDays: 18 * DAY, minBalance: 100000n, requireAge: true, requireBalance: true, requireAccredited: true, maxClockSkewDays: 2, active: true },
  { name: "Solvent over 10k", issuerPubX, issuerPubY, minAgeDays: 0, minBalance: 10000n, requireAge: false, requireBalance: true, requireAccredited: false, maxClockSkewDays: 2, active: true },
];
for (const p of policies) {
  await wait(await registry.write.publishPolicy([p], { account: admin.account }));
  console.log(`policy published: ${p.name}`);
}

const outDir = path.resolve(process.cwd(), "../frontend/src/generated");
mkdirSync(outDir, { recursive: true });
const deployment = {
  chainId: 31337,
  rpcUrl: "http://127.0.0.1:8549",
  deployedAt: new Date().toISOString(),
  issuerLabel: ISSUER_LABEL,
  issuerPubX,
  issuerPubY,
  contracts: { registry: registry.address, verifier: verifier.address },
  admin: admin.account.address,
  holders: [alice.account.address, bob.account.address, carol.account.address],
  policies: policies.map((p, i) => ({
    policyId: i + 1,
    name: p.name,
    minAgeDays: p.minAgeDays,
    minBalance: Number(p.minBalance),
    requireAge: p.requireAge,
    requireBalance: p.requireBalance,
    requireAccredited: p.requireAccredited,
  })),
};
writeFileSync(path.join(outDir, "deployment.json"), JSON.stringify(deployment, null, 2));
console.log(`deployment written to ${path.join(outDir, "deployment.json")}`);

let out = "// GENERATED by contracts/scripts/deploy-local.ts — do not edit.\n";
for (const [artifact, name] of [["VouchRegistry", "vouchRegistryAbi"], ["Groth16Verifier", "groth16VerifierAbi"]] as const) {
  const a = await hre.artifacts.readArtifact(artifact);
  out += `\nexport const ${name} = ${JSON.stringify(a.abi, null, 2)} as const;\n`;
}
writeFileSync(path.join(outDir, "abis.ts"), out);
console.log(`ABIs written to ${path.join(outDir, "abis.ts")}`);
