import { useState } from "react";

/**
 * The finding that the zero-knowledge claim does NOT cover, made visible.
 *
 * The circuit's nullifiers are unlinkable across contexts, and the audit proves it. But the
 * registry emits Cleared(policyId, msg.sender, nullifier), so an observer reading the chain
 * correlates every claim one ADDRESS made — without breaking any cryptography at all.
 *
 * The toggle shows the fix: a fresh address per policy, and the profile falls apart.
 */
const POLICIES = [
  { id: 1, name: "Over 18", asker: "NightOwl Spirits", reveals: "is an adult" },
  { id: 2, name: "Accredited investor", asker: "Meridian Ventures", reveals: "has investor status" },
  { id: 3, name: "Solvent over 10k", asker: "Harbour Lofts", reveals: "holds reserves" },
];

// real nullifiers, from proofs generated by ONE holder across the three contexts
const NULLIFIERS: Record<number, string> = {
  1: "14992545762035118727…",
  2: "15144973571964749247…",
  3: "91178473299918362532…",
};
const ONE_ADDRESS = "0x7099…79c8";
const FRESH: Record<number, string> = { 1: "0x7099…79c8", 2: "0x3c44…93bc", 3: "0x90f7…b906" };

export function Linkability() {
  const [cleared, setCleared] = useState<number[]>([]);
  const [freshAddress, setFreshAddress] = useState(false);

  const rows = POLICIES.filter((p) => cleared.includes(p.id));
  const linked = !freshAddress && rows.length > 1;

  return (
    <div className="card">
      <h3>What the chain gives away anyway</h3>
      <p className="muted small">
        The circuit does its job: proving three different claims produces three unrelated
        nullifiers, and no verifier can tell they came from one person. Then the registry
        publishes <span className="mono">Cleared(policyId, msg.sender, nullifier)</span> — and an
        observer correlates them from the address, with no cryptography broken. Clear some policies
        and watch.
      </p>

      <div className="link-controls">
        {POLICIES.map((p) => (
          <button
            key={p.id}
            className={cleared.includes(p.id) ? "btn primary" : "btn"}
            onClick={() => setCleared((c) => c.includes(p.id) ? c.filter((x) => x !== p.id) : [...c, p.id])}
          >
            {cleared.includes(p.id) ? "✓ " : ""}{p.name}
          </button>
        ))}
        <label className="link-toggle">
          <input type="checkbox" checked={freshAddress} onChange={(e) => setFreshAddress(e.target.checked)} />
          <span>use a fresh address per policy</span>
        </label>
      </div>

      <div className="link-panes">
        <div className="link-pane">
          <h4>What is on the chain</h4>
          {rows.length === 0 ? (
            <p className="muted small">Nothing yet. Clear a policy above.</p>
          ) : (
            <table className="tbl">
              <thead><tr><td>policy</td><td>address</td><td>nullifier</td></tr></thead>
              <tbody>
                {rows.map((p) => (
                  <tr key={p.id}>
                    <td className="small">{p.name}</td>
                    <td className="mono small">{freshAddress ? FRESH[p.id] : ONE_ADDRESS}</td>
                    <td className="mono small">{NULLIFIERS[p.id]}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          )}
          <p className="muted small">
            Three unrelated nullifiers — the circuit kept its promise. No birthday, no balance.
          </p>
        </div>

        <div className="link-pane">
          <h4>What an observer concludes</h4>
          {rows.length === 0 ? (
            <p className="muted small">—</p>
          ) : linked ? (
            <>
              <div className="profile">
                <div className="profile-h mono">{ONE_ADDRESS}</div>
                <ul>{rows.map((p) => <li key={p.id}>{p.reveals}</li>)}</ul>
              </div>
              <p className="bad-line small">
                One person, {rows.length} facts, assembled for free. The values stayed hidden. The
                correlation did not. If that address ever touches a KYC'd exchange or an ENS name,
                the whole profile has a name on it.
              </p>
            </>
          ) : freshAddress ? (
            <>
              {rows.map((p) => (
                <div key={p.id} className="profile solo">
                  <div className="profile-h mono">{FRESH[p.id]}</div>
                  <ul><li>{p.reveals}</li></ul>
                </div>
              ))}
              <p className="ok-line small">
                {rows.length === 1
                  ? "One address, one claim. Nothing to correlate yet."
                  : `${rows.length} unrelated addresses. Nothing ties them together — this is the fix, and it costs a wallet, not a circuit change.`}
              </p>
            </>
          ) : (
            <>
              <div className="profile">
                <div className="profile-h mono">{ONE_ADDRESS}</div>
                <ul>{rows.map((p) => <li key={p.id}>{p.reveals}</li>)}</ul>
              </div>
              <p className="muted small">One claim so far. Clear a second to see them join up.</p>
            </>
          )}
        </div>
      </div>

      <p className="muted small">
        We found this by querying our own chain, not by being told. The cryptography was never the
        weak layer — the deployment was. It is written up in <span className="mono">docs/WORTH.md</span>.
      </p>
    </div>
  );
}
