import type { VercelRequest, VercelResponse } from "@vercel/node";

/**
 * GENERATED by scripts/gen-issuer-key.mjs -- do not edit.
 *
 * Who is vouching. The key is a pure function of ISSUER_SECRET, so it is derived at build
 * time and inlined here: this endpoint imports nothing but types, loads no curve, and has
 * nothing that can fail at cold start.
 */
export default function handler(_req: VercelRequest, res: VercelResponse) {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.status(200).json({
    name: "Demo KYC Provider",
    pubX: "16256427309067318996113477331037527797444329102066601306330596369324314410467",
    pubY: "5404833324877437496892341675876228763119597194797211767738034807954009477490",
    issuedCount: 0,
  });
}
